#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="${ARKSPACE_E2E_ENV_FILE:-.env.e2e}"
umask 077

require_nonempty() {
  local name="$1" value="$2"
  [[ -n "$value" ]] || { warn "$name cannot be empty"; exit 1; }
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || { warn "$name must be one line"; exit 1; }
}

set_environment_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --env provider-e2e >/dev/null 2>&1; then
      WRITTEN_SECRET+=("provider-e2e/$name")
      printf '  %s✓ set%s GitHub environment secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub provider-e2e secret $name")
  warn "could not set provider-e2e/$name; configure it manually"
}

banner "ArkSpace release and Provider E2E setup"

stage "Exa — disposable API key"
say "Use a dedicated low-quota test account. Never paste a production key."
open_url "https://dashboard.exa.ai/"
step "Open API Keys, create or copy a disposable test key, and return here."
ask_secret EXA_API_KEY "Paste the Exa test key:"
require_nonempty EXA_API_KEY "$EXA_API_KEY"
write_env EXA_API_KEY "$EXA_API_KEY"

stage "Tavily — disposable API key"
say "Use a dedicated low-quota test account."
open_url "https://app.tavily.com/"
step "Open the API key area, create or copy a test key, and return here."
ask_secret TAVILY_API_KEY "Paste the Tavily test key:"
require_nonempty TAVILY_API_KEY "$TAVILY_API_KEY"
write_env TAVILY_API_KEY "$TAVILY_API_KEY"

stage "Firecrawl — disposable API key"
say "The E2E suite creates Browser and Site Monitor resources, so use a capped test account."
open_url "https://www.firecrawl.dev/app"
step "Open API Keys, create or copy a disposable test key, and return here."
ask_secret FIRECRAWL_API_KEY "Paste the Firecrawl test key:"
require_nonempty FIRECRAWL_API_KEY "$FIRECRAWL_API_KEY"
write_env FIRECRAWL_API_KEY "$FIRECRAWL_API_KEY"

stage "Public test webhook"
say "Use an isolated HTTPS receiver that discards test Exa Monitor deliveries."
step "Create the endpoint in your test webhook service and copy its HTTPS URL."
ask_secret ARKSPACE_E2E_WEBHOOK_URL "Paste the public HTTPS webhook URL:"
require_nonempty ARKSPACE_E2E_WEBHOOK_URL "$ARKSPACE_E2E_WEBHOOK_URL"
[[ "$ARKSPACE_E2E_WEBHOOK_URL" == https://* ]] || { warn "The webhook URL must start with https://"; exit 1; }
write_env ARKSPACE_E2E_WEBHOOK_URL "$ARKSPACE_E2E_WEBHOOK_URL"
chmod 600 "$ENV_FILE" 2>/dev/null || true

stage "GitHub protected E2E environment"
say "The manual Provider E2E workflow reads four secrets from the provider-e2e environment."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  REPOSITORY_URL=$(gh repo view --json url --jq .url 2>/dev/null || true)
  if [[ -n "$REPOSITORY_URL" ]]; then
    gh api --method PUT "repos/{owner}/{repo}/environments/provider-e2e" >/dev/null
    open_url "$REPOSITORY_URL/settings/environments"
    step "Open provider-e2e, add required reviewers, and prevent self-review when available."
    pause "Press Enter after the protection rules are saved."
    set_environment_secret EXA_API_KEY "$EXA_API_KEY"
    set_environment_secret TAVILY_API_KEY "$TAVILY_API_KEY"
    set_environment_secret FIRECRAWL_API_KEY "$FIRECRAWL_API_KEY"
    set_environment_secret ARKSPACE_E2E_WEBHOOK_URL "$ARKSPACE_E2E_WEBHOOK_URL"
  else
    SKIPPED+=("GitHub provider-e2e environment; no repository remote was detected")
    warn "No GitHub repository remote was detected. Configure the environment after adding one."
  fi
else
  SKIPPED+=("GitHub provider-e2e environment; install and authenticate gh")
  warn "gh is unavailable or unauthenticated. Configure the protected environment manually."
fi

stage "Release identity"
say "These are public release facts. They are written to release/identity.json, never to the secret env file."
ask ARKSPACE_NPM_PACKAGE "Confirmed npm package name (for example @arkspace/cli):"
ask ARKSPACE_REPOSITORY_URL "Canonical public repository URL:"
ask ARKSPACE_COPYRIGHT_HOLDER "Copyright holder exactly as LICENSE should name it:"
require_nonempty ARKSPACE_NPM_PACKAGE "$ARKSPACE_NPM_PACKAGE"
require_nonempty ARKSPACE_REPOSITORY_URL "$ARKSPACE_REPOSITORY_URL"
require_nonempty ARKSPACE_COPYRIGHT_HOLDER "$ARKSPACE_COPYRIGHT_HOLDER"
mkdir -p release
node - "$ARKSPACE_NPM_PACKAGE" "$ARKSPACE_REPOSITORY_URL" "$ARKSPACE_COPYRIGHT_HOLDER" <<'NODE'
const [npmPackage, repositoryUrl, copyrightHolder] = process.argv.slice(2);
require("node:fs").writeFileSync("release/identity.json", `${JSON.stringify({ npmPackage, repositoryUrl, copyrightHolder }, null, 2)}\n`, { mode: 0o644 });
NODE
printf '  %s✓ wrote%s release/identity.json\n' "$GREEN" "$RESET"
note "An agent must still align package.json and LICENSE, and explicit authorization is required before private:true is removed."

stage "Run credentialed Provider E2E"
warn "This creates paid jobs, a Browser session, an Exa Monitor, and a Firecrawl Site Monitor."
say "ArkSpace attempts cleanup on success, failure, SIGINT, and SIGTERM. A hard kill or acceptance-unknown create still requires dashboard cleanup."
if confirm "Run npm run test:e2e now and accept remote charges?"; then
  export EXA_API_KEY TAVILY_API_KEY FIRECRAWL_API_KEY ARKSPACE_E2E_WEBHOOK_URL
  export ARKSPACE_E2E_CONFIRM="I_ACCEPT_REMOTE_CHARGES_AND_PERSISTENT_RESOURCES"
  if npm run test:e2e; then
    note "Record the date, commit, Node/OS, and redacted test-account IDs in the release checklist."
  else
    warn "E2E failed. Inspect all Provider dashboards and remove every ArkSpace release E2E resource before retrying."
    exit 1
  fi
else
  SKIPPED+=("credentialed npm run test:e2e")
  note "Re-run this wizard when ready; it remembers values in $ENV_FILE without printing them."
fi

finish
